spring:
  datasource:
    url: jdbc:mysql://192.168.18.222:3306/face_identify_mng?useSSL=false&characterEncoding=utf8
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root