server:
  port: 8080
  context-path: /client
security:
  oauth2:
    client:
      client-id: testClientId
      client-secret: testClientSecret
      access-token-uri: http://localhost:8082/server/oauth/token
      user-authorization-uri: http://localhost:8082/server/oauth/authorize
      #      clientAuthenticationScheme: form
      resource:
      #      userInfoUri: http://localhost:8082/me
      token-info-uri: http://localhost:8082/server/oauth/check_token
